arq_db_cp = 'DATA_BASE/SICRO_GO_10_2020_analitico_composicao_dado_basico.txt'
arq_db_in = 'DATA_BASE/SICRO_GO_10_2020_sintetico_dado_basico.txt'
arq_apr_in = 'DATA_BASE/SICRO_GO_10_2020_analitico_composicao_apropriacao.txt'
arq_cto_in = 'DATA_BASE/SICRO_GO_10_2020_sintetico_custo_unitario.txt'
arq_db_al_an = 'REPOSITORIO/SICRO_ZZ_00_0000_analitico_administracao_local_dado_basico.txt'
arq_apr_al = 'REPOSITORIO/SICRO_ZZ_00_0000_analitico_administracao_local_apropriacao.txt'
arq_db_al_st = 'REPOSITORIO/SICRO_ZZ_00_0000_sintetico_administracao_local_dado_basico.txt'
arq_dmt = 'REPOSITORIO/dmt_material.txt'