UTF='utf-8'
EQUIPAMENTO = 20
EQUIPAMENTO_CUSTO_HORARIO = 21
MAO_DE_OBRA = 30
MAO_DE_OBRA_CUSTO_HORARIO = 31
EXECUCAO_HORARIO = 32
EXECUCAO_UNITARIO = 33
MATERIAL = 40
MATERIAL_CUSTO_UNITARIO = 41
ATIVIDADE_AUXILIAR = 50
ATIVIDADE_AUXILIAR_CUSTO_TOTAL = 51
TEMPO_FIXO = 60
TEMPO_FIXO_CUSTO_TOTAL = 61
TRANSPORTE = 70
TRANSPORTE_CUSTO_TOTAL = 71
DIRETO_TOTAL_UNITARIO = 80
CODIGO_HORARIO = 'ho'
CODIGO_HORARIO_EXECUCAO = 'ho_ex'
CODIGO_UNITARIO = 'un'
CODIGO_UNITARIO_DIRETO_TOTAL = 'un_dt'
COLUNAS_DF_ORIGEM_CP = ['Origem', 'Estado', 'Publicacao']
COLUNAS_DF_DADOS_BASICO_CP = ['Composicao_principal', 'FIC', 'Produtividade', 'Tipo', 'NONE']
COLUNAS_DF_DADOS_BASICO_IN = ['Código', 'Descrição', 'Unidade', 'NONE']
COLUNAS_DF_APROPRIACAO_IN = ['Composicao_principal', 'Código', 'Quantidade', 'Utilização', 'Item transporte','Grupo','NONE']
COLUNAS_DF_CUSTO_IN = ['Código', 'Custo pro onerado', 'Custo imp onerado', 'Custo pro desonerado', 'Custo imp desonerado', 'Preço unitário', 'Grupo', 'NONE']
